### ISSUE TITLE
Splash screen not appearing when launching app

### ISSUE THREAD

**Issue by divyesh26** [coval-solutions/bfit-tracker-app#19]
Splash screen could be placed before login widget, not after. Hence, does not launch every time you open app.

**Comment by DiogoTheCoder** [comment]
> Splash screen could be placed before login widget, not after. Hence, does not launch every time you open app.

Hi @divyesh26 👋,

Thanks for bringing this to our attention. We have opened a pull request which aims to resolve this issue (https://github.com/coval-solutions/bfit-tracker-app/pull/20).

Cheers,

@DiogoTheCoder
